= Introduction à JPA
:toc:

== Présentation

JPA est une interface de programmation permettant d'utiliser un modèle objet
au-dessus d'une base de données relationnelle.

JPA associe un graphe de classes Java aux tables d'une base de données
relationnelle par le biais :

* de fichiers de configuration xml
* d'annotations depuis Java 5 (c'est la méthode préférée)

Pour la suite nous utiliserons le modèle suivant :

.Modèle d'analyse du domaine
[plantuml]
----
Object Article{
id
title
headline
content
slug
addedAt
}
Object Person{
id
login
firstname
lastname
description
}

Article" * " - "credited 1" Person :"\t\t\t\t\t"

----

Dans ce modèle une personne peut écrire plusieurs articles (liste de type `Article`), et un article est crédité par une seule source (de type `Person`).

Une application JPA se divise en deux parties :

- Définir le modèle de données (graphe d'objets)
- Gérer l'accès aux données (créer, récupérer, modifier et supprimer les données)

== Définir le modèle

=== Une traduction de l'analyse

Le modèle qui nous intéresse ici est celui centré sur la logique métier du client, les données qu'ils manipulent. Ces données sont regroupées en *entités*, qui, dans le code, sont représentées par des *classes*, dites *métier*, parfois stéréotypées \<<entity>> dans les diagrammes d'analyse.

TIP: Il est fort pratique de représenter l'analyse sous la forme d'un diagramme de classes UML, car, en conception (design), l'analyse permet au développeur de se consacrer sur les détails des entités sans perdre le fil de leurs relations.

=== Associer une table à une classe, les entités (entities)

.Classe Person associée à la table `Person` (sans référence à d'autres entités)
[source,kotlin]
----

@Entity <1>
@Table(name = "Person") <2>
class Person(

    @Column(name = "login", unique = true, nullable = false, length = 20) <3>
    var login: String, <4>

    @Column(name = "firstname", nullable = false)
    var firstname: String,

    @Column(name = "lastname", nullable = false)
    var lastname: String,

    @Column(columnDefinition="TEXT")
    var description: String? = null,

    @Id <5>
    @GeneratedValue(strategy = GenerationType.IDENTITY) <6>
    @Column(name = "id", nullable = false)
    var id: Long? = null) <7>

----

<1> `@Entity` déclare la classe comme un objet persistant
associé par défaut à la table de même nom (à la casse près).
<2> `@Table` déclare le nom de la table associée à la classe, indispensable
si les deux noms diffèrent (ce n'est pas le cas ici).
<3> `@Column` permet d'établir la correspondance entre la propriété de la classe
et la colonne de la table, ainsi que certaines règles de validation comme
l'interdiction de nullité, la longueur, le type...
<4> La propriété associée à la colonne de la table (valeur d'attribut).
<5> `@Id` déclare l'attibut comme clé primaire, au moins un attribut doit
être marqué par cette annotation
<6> `@GeneratedValue` indique que la valeur est générée automatiquement
<7> Bien que la colonne associée soit déclarée non nullable (c'est une PK), la propriété `id` l'est ! (son type est `Long?`) En effet, à la création d'un *nouvel* objet en mémoire, alors qu'il n'est pas encore persisté (associé à aucune ligne dans la table), l'objet n'a pas encore de valeur d'identifiant de base de données. Cette valeur lui sera attribuée par le SGBD lors de sa sauvegarde dans la base (donc dans un second temps)

[IMPORTANT]
====
Le mécanisme qui assure la correspondance entre une Classe Entity et une Table d'une base de données est appelé *ORM* (_Object Relational Mapping_)

_Un mapping objet-relationnel (en anglais object-relational mapping ou ORM) est un type de programme informatique qui se place en interface entre un programme applicatif et une base de données relationnelle pour simuler une base de données orientée objet. Ce programme définit des correspondances entre les schémas de la base de données et les classes du programme applicatif. On pourrait le désigner par là, « comme une couche d'abstraction entre le monde objet et monde relationnel ». Du fait de sa fonction, on retrouve ce type de programme dans un grand nombre de frameworks sous la forme de composant ORM qui a été soit développé, soit intégré depuis une solution externe._ source : https://fr.wikipedia.org/wiki/Mapping_objet-relationnel

Ainsi, à une *instance* d'une classe Entity correspond une *ligne* d'une table d'une base de données relationnelle.

====

=== Gérer les associations (`ManyToOne` et `OneToMany`)

Dans ce modèle un Person peut écrire plusieurs articles, et un article est crédité par une seule personne.

.Modèle d'analyse du domaine
[plantuml]
----
Object Article{
id
title
headline
content
slug
addedAt
}
Object Person{
id
login
firstname
lastname
description
}

Article" * " - "creditedTo 1" Person :"\t\t\t\t"

----

L'association de `Article` vers `Person` est de type `ManyToOne`. Cette même association vue côté `Person` est de type `OneToMany` vers `Article`.

Si l'association est bidirectionnelle, la classe côté `ManyToOne` (dans notre cas `Article`) est dite propriétaire (_owner_) de l'association car sa table associée détient la clé étrangère de la relation. Le côté non propriétaire, ici `Person`, doit utiliser l'élément _mappedBy_ de l'annotation pour spécifier l'attribut du côté propriétaire. Pour les données en base, le système assure la cohérence des liens entre objets en mémoire. Par contre, en cas gestion mémoire de ces liens par la logique applicative, la cohérence est du ressort du développeur.

.La classe Article
[source,kotlin]
----
@Entity
class Article(
    var title: String,
    var headline: String,
    var content: String,

    @ManyToOne <1>
    @JoinColumn(name = "credited_to_id") <2>
    var creditedTo: Person, <3>

    var slug: String = title.toSlug(),
    var addedAt: LocalDateTime = LocalDateTime.now(),
    @Id @GeneratedValue var id: Long? = null)

----
<1> L'annotation `@ManyToOne` permet de savoir que l'objet annoté doit être retrouvé dans une autre table. Le paramètre `FetchType` permet de savoir s'il faut immédiatement retrouver l'objet lié (`EAGER`) ou s'il faut le retrouver seulement lorsqu'il est accédé dans l'application (`LAZY`). La deuxième option diffère la requête SQL jusqu'à ce que l'application cherche à accéder à l'objet Person
<2> L'annotation `@JoinColumn` permet à l'application de déterminer quelle colonne dans la table sert de clé étrangère pour retrouver l'objet lié
<3> Si `credited_to_id` est une clé étrangère et un entier, la propriété associée, nommée `creditedTo`, est de type `*Person*`.

[IMPORTANT]
====
Ne pas confondre clé étrangère et propriété de l'association.

`credited_to_id` est le nom de la colonne dans la table (une clé étrangère), la propriété `creditedTo` lie une instance d'`Article` à une instance de `Person`.

*Avec JPA le développeur gère un graphe d'objets, pas une base de données SQL.*
====

.Classe Person et associaton bidirectionnelle avec Article
[source,kotlin]
----

@Entity
class Person(

    @Column(name = "login", unique = true, nullable = false, length = 20)
    var login: String,

    @Column(name = "firstname", nullable = false)
    var firstname: String,

    @Column(name = "lastname", nullable = false)
    var lastname: String,

    @Column(columnDefinition="TEXT")
    var description: String? = null,

    @OneToMany(mappedBy = "creditedTo", cascade = [CascadeType.ALL]) <1>
    var articles: MutableList<Article> = mutableListOf(), <2>

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    var id: Long? = null)

----
<1> `@OneToMany` indique qu'une instance de `Person` peut être liée à plusieurs instances de `Article`, en tant qu'auteur, c'est la propriété `creditedTo` dans `Article` qui représente ce lien
<2> Une personne pouvant réaliser plusieurs articles, les références à ses articles sont stockés dans une collection mutable, qui peut être vide.

== Gérer l'accès aux données, les dépôts (repositories)

=== Présentation

Si les classes Entity permettent de définir les structures de données et la façon dont les objets sont liés aux tables SQL, elles ne permettent pas de manipuler les tables : créer, lire, mettre à jour ou supprimer des données. En anglais ces actions sont connues sous le nom de `CRUD` (_Create_, _Read_, _Update_, _Delete_). Les objets qui permettent de faire des opérations de type `CRUD` sur une base de données sont appelés des DAO (Data Access Object).

Créer des DAOs est une tâche répétitive et ingrate, 90% du code est
similaire d'un DAO à l'autre. Spring propose une méthode standard pour
gérer les DAOs au travers d'objets, ou plutôt d'interfaces, de type
`CrudRepository`, `PagingAndSortingRepository
` ou `JpaRepository` qui hérite de la classe précédente. Dans les cas simples `CrudRepository` suffit largement.

=== L'interface CrudRepository

Permet d'effectuer toutes les opérations de base d'un DAO :

* `long count()` : compte le nombre d'entités disponibles
* `void delete(T entity)` : supprime l'entité passée en paramètre
* `void deleteAll()` : supprime toutes les entités
* `void deleteById(ID id)` : supprime une entité avec l'id passé en paramètre
* `void existsById(ID id)` : retourne vrai si une entité avec l'id passé en paramètre existe
* `Iterable<T> findAll()` : retourne toutes les instances du type
* `Iterable<T> findAllById(Iterable<ID> id)` :
* `Optional<T> findById(ID id)` : retrouve une entité par son id
* `<S extends T> S save(S entity)` : sauvegarde une entité donnée
* `<S extends T> Iterable<S> saveAll(Iterable<S> entities)` : sauvegarde toutes les entités passées en paramètre.

Ci-dessous un exemple de CrudRepository :

[source,kotlin]
----
package com.example.demo.repository

import com.example.demo.model.Person
import org.springframework.data.repository.CrudRepository

interface PersonRepository : CrudRepository<Person, Long> {

}

----

TIP: L'implémentation de l'interface est réalisée *automatiquement* par le framework.

== Exemple de configuration d'un projet Spring Boot avec JPA

.Exemple avec H2 (src/main/resources/application.properties)
[source,properties]
----

# Connexion à la base de données
spring.datasource.url=jdbc:h2:file:c:/db/blog;AUTO_SERVER=true <1>
#spring.datasource.url=jdbc:h2:file:~/db/blog;AUTO_SERVER=true <2>
spring.datasource.driver-class-name=org.h2.Driver <3>
spring.datasource.username=sa <4>
spring.datasource.password= <5>
spring.jpa.hibernate.ddl-auto=create-drop <6>
spring.datasource.initialization-mode=always <7>
spring.h2.console.enabled=true <8>
----

<1> Chaîne JDBC de connexion à la base de données, version Windows
<2> La même version Linux ou Mac. `;AUTO_SERVER=true` permet une connexion par des tiers comme intellij... (H2 mixed mode)
<3> Driver JDBC à utiliser
<4> Utilisateur pour accéder à la source de données JDBC
<5> Mot de passe de l'utlisateur
<6> Le schéma de la base de données est généré à partir des entités JPA, à chaque exécution de l'application les tables sont supprimées et recrées, l'option `create-drop` n'est valable que pour la phase de développement, en production on utilise l'option `none`

<7> Si un fichier `data.sql`est présent, il est automatiquement utilisé pour importer les données qu'il contient dans la base de données
<8> Propre à `H2` (driver par défaut). Permet d'accéder à la console H2, une fois que l'application lancée, à l'URL `http://localhost:8080/h2-console`, il s'agit d'une application web intégrée au moteur H2 permettant de manipuler la base de données.


Voici un exemple avec MysSql : https://spring.io/guides/gs/accessing-data-mysql/

== Travaux pratiques

Vous étudiez un début d'application web, structurée en couches minimales, et vous réalisez les travaux attendus.

Les explications et le travail à faire se trouvent dans le README.adoc du projet.

https://github.com/ldv-melun/app-spring-boot-kotlin-jpa-first